# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(800, 440))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralWidget.setFont(font)
        self.centralWidget.setObjectName("centralWidget")
        self.TabBar = QtWidgets.QTabWidget(self.centralWidget)
        self.TabBar.setGeometry(QtCore.QRect(0, 0, 800, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabBar.sizePolicy().hasHeightForWidth())
        self.TabBar.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.TabBar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TabBar.setFont(font)
        self.TabBar.setAutoFillBackground(False)
        self.TabBar.setStyleSheet("background-color: rgb(83, 81, 90);\n"
"\n"
"")
        self.TabBar.setObjectName("TabBar")
        self.Home = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home.sizePolicy().hasHeightForWidth())
        self.Home.setSizePolicy(sizePolicy)
        self.Home.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Home.setStyleSheet("ui->Wdgt_Inbox->tabBar()->setCurrentIndex(0);\n"
"ui->Wdgt_Inbox->tabBar()->setStyleSheet(\"background-color:grey;\");\n"
"ui->Wdgt_Inbox->tabBar()->setStyleSheet(\"QWidget { background-color:grey; }\");\n"
"ui->Tab_Inbox->setStyleSheet(\"background-color:grey;\");")
        self.Home.setObjectName("Home")
        self.JumpProject = QtWidgets.QPushButton(self.Home)
        self.JumpProject.setGeometry(QtCore.QRect(30, 280, 361, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.JumpProject.setFont(font)
        self.JumpProject.setStyleSheet("background-color: rgb(161, 164, 163);\n"
"border-bottom-left-radius: 7px;\n"
"color: rgb(55, 52, 48);\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/Icons/Plus36.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.JumpProject.setIcon(icon)
        self.JumpProject.setObjectName("JumpProject")
        self.label_3 = QtWidgets.QLabel(self.Home)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 731, 131))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(39)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgb(22, 27, 34);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.Home)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 731, 141))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-top-right-radius: 7px;\n"
"border-top-left-radius: 7px;\n"
"background-color: rgb(22, 27, 34);\n"
"\n"
"\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/new/prefix1/Icons/Pig80.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Home)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 731, 271))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-width: 3px;\n"
"border-color: rgb(161, 164, 163);\n"
"border-top-right-radius: 7px;\n"
"border-top-left-radius: 7px;\n"
"border-style: solid;\n"
"\n"
"\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.JumpManual = QtWidgets.QPushButton(self.Home)
        self.JumpManual.setGeometry(QtCore.QRect(390, 280, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.JumpManual.setFont(font)
        self.JumpManual.setStyleSheet("background-color: rgb(161, 164, 163);\n"
"border-bottom-right-radius: 7px;\n"
"color: rgb(55, 52, 48);\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/prefix1/Icons/Hand36.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.JumpManual.setIcon(icon1)
        self.JumpManual.setObjectName("JumpManual")
        self.line = QtWidgets.QFrame(self.Home)
        self.line.setGeometry(QtCore.QRect(390, 290, 3, 60))
        self.line.setStyleSheet("border-style:solid;\n"
"border-width:1px;\n"
"border-color: rgb(172, 99, 22);\n"
"background-color: rgb(172, 99, 22);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.Home)
        self.line_2.setGeometry(QtCore.QRect(390, 300, 3, 61))
        self.line_2.setStyleSheet("border-style:solid;\n"
"border-width:1px;\n"
"border-color: rgb(172, 99, 22);\n"
"background-color: rgb(172, 99, 22);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtWidgets.QLabel(self.Home)
        self.label_9.setGeometry(QtCore.QRect(470, 230, 35, 10))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_9.setObjectName("label_9")
        self.JumpManual.raise_()
        self.JumpProject.raise_()
        self.label_7.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.label_9.raise_()
        self.TabBar.addTab(self.Home, "")
        self.Project = QtWidgets.QWidget()
        self.Project.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Project.setObjectName("Project")
        self.LoadFile = QtWidgets.QPushButton(self.Project)
        self.LoadFile.setGeometry(QtCore.QRect(20, 350, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.LoadFile.setFont(font)
        self.LoadFile.setStyleSheet("background-color: rgb(172, 99, 22);\n"
"border-style:solid;\n"
"border-bottom-right-radius:3px;\n"
"border-bottom-left-radius:3px;\n"
"color:rgb(161, 164, 163);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/prefix1/Icons/Plus25_whitish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LoadFile.setIcon(icon2)
        self.LoadFile.setObjectName("LoadFile")
        self.Start = QtWidgets.QPushButton(self.Project)
        self.Start.setGeometry(QtCore.QRect(260, 30, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.Start.setFont(font)
        self.Start.setStyleSheet("background-color: rgb(172, 99, 22);\n"
"border-style: solid;\n"
"border-radius: 4px;\n"
"color:rgb(161, 164, 163);")
        self.Start.setObjectName("Start")
        self.SpeedSliderProj = QtWidgets.QSlider(self.Project)
        self.SpeedSliderProj.setGeometry(QtCore.QRect(480, 100, 161, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 81, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.SpeedSliderProj.setPalette(palette)
        self.SpeedSliderProj.setStyleSheet("color: rgb(172, 99, 22)")
        self.SpeedSliderProj.setMaximum(200)
        self.SpeedSliderProj.setSliderPosition(100)
        self.SpeedSliderProj.setOrientation(QtCore.Qt.Horizontal)
        self.SpeedSliderProj.setObjectName("SpeedSliderProj")
        self.ProgressBar = QtWidgets.QProgressBar(self.Project)
        self.ProgressBar.setGeometry(QtCore.QRect(480, 30, 271, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 99, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 164, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 32, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.ProgressBar.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.ProgressBar.setFont(font)
        self.ProgressBar.setStyleSheet("color: rgb(161, 164, 163);\n"
"background-color: rgb(27, 32, 39);\n"
"border-style:solid;\n"
"border-width:1px;\n"
"border-color: rgb(172, 99, 22);\n"
"border-radius:5px;\n"
"")
        self.ProgressBar.setMaximum(150)
        self.ProgressBar.setProperty("value", 20)
        self.ProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.ProgressBar.setObjectName("ProgressBar")
        self.FileSelector = QtWidgets.QListWidget(self.Project)
        self.FileSelector.setGeometry(QtCore.QRect(20, 30, 221, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileSelector.sizePolicy().hasHeightForWidth())
        self.FileSelector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.FileSelector.setFont(font)
        self.FileSelector.setStyleSheet("background-color: rgb(27, 32, 39);\n"
"border-top-left-radius: 3px;\n"
"border-top-right-radius: 3px;\n"
"border-style: solid;\n"
"border-color:rgb(172, 99, 22);\n"
"border-width:1px;\n"
"color: rgb(161, 164, 163);\n"
"")
        self.FileSelector.setObjectName("FileSelector")
        self.Pause = QtWidgets.QPushButton(self.Project)
        self.Pause.setGeometry(QtCore.QRect(260, 100, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.Pause.setFont(font)
        self.Pause.setStyleSheet("background-color: rgb(172, 99, 22);\n"
"border-style: solid;\n"
"border-radius: 4px;\n"
"color: rgb(161, 164, 163) ")
        self.Pause.setObjectName("Pause")
        self.Stop = QtWidgets.QPushButton(self.Project)
        self.Stop.setGeometry(QtCore.QRect(260, 170, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.Stop.setFont(font)
        self.Stop.setStyleSheet("background-color: rgb(172, 99, 22);\n"
"border-style: solid;\n"
"border-radius: 4px;\n"
"color: rgb(161, 164, 163);")
        self.Stop.setObjectName("Stop")
        self.FileDescription = QtWidgets.QLabel(self.Project)
        self.FileDescription.setGeometry(QtCore.QRect(260, 240, 491, 141))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.FileDescription.setFont(font)
        self.FileDescription.setStyleSheet("background-color: rgb(27, 32, 39);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 4px;\n"
"border-color:rgb(172, 99, 22)")
        self.FileDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.FileDescription.setObjectName("FileDescription")
        self.TimeEstimate = QtWidgets.QLabel(self.Project)
        self.TimeEstimate.setGeometry(QtCore.QRect(480, 70, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.TimeEstimate.setFont(font)
        self.TimeEstimate.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.TimeEstimate.setObjectName("TimeEstimate")
        self.label_10 = QtWidgets.QLabel(self.Project)
        self.label_10.setGeometry(QtCore.QRect(660, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.LoadFile.raise_()
        self.Start.raise_()
        self.SpeedSliderProj.raise_()
        self.ProgressBar.raise_()
        self.Pause.raise_()
        self.Stop.raise_()
        self.FileSelector.raise_()
        self.FileDescription.raise_()
        self.TimeEstimate.raise_()
        self.label_10.raise_()
        self.TabBar.addTab(self.Project, "")
        self.Manual = QtWidgets.QWidget()
        self.Manual.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Manual.setObjectName("Manual")
        self.pushButton_6 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_6.setGeometry(QtCore.QRect(530, 230, 41, 41))
        self.pushButton_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Icons/RightR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.Manual)
        self.label_4.setGeometry(QtCore.QRect(450, 230, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Manual)
        self.label_5.setGeometry(QtCore.QRect(610, 230, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_8.setGeometry(QtCore.QRect(460, 300, 41, 41))
        self.pushButton_8.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Icons/DownR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_9.setGeometry(QtCore.QRect(390, 230, 41, 41))
        self.pushButton_9.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Icons/LeftR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_7.setGeometry(QtCore.QRect(460, 160, 41, 41))
        self.pushButton_7.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Icons/UpR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_10.setGeometry(QtCore.QRect(620, 160, 41, 41))
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_11.setGeometry(QtCore.QRect(620, 300, 41, 41))
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.Manual)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(440, 380, 160, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_12.setGeometry(QtCore.QRect(330, 20, 41, 41))
        self.pushButton_12.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Icons/Temple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon7)
        self.pushButton_12.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_13.setGeometry(QtCore.QRect(330, 70, 41, 41))
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon7)
        self.pushButton_13.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.Manual)
        self.pushButton_14.setGeometry(QtCore.QRect(330, 120, 41, 41))
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon7)
        self.pushButton_14.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.TabBar.addTab(self.Manual, "")
        self.Error = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Error.sizePolicy().hasHeightForWidth())
        self.Error.setSizePolicy(sizePolicy)
        self.Error.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Error.setObjectName("Error")
        self.label_6 = QtWidgets.QLabel(self.Error)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 771, 391))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.TabBar.addTab(self.Error, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.TabBar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.JumpProject.setText(_translate("MainWindow", " new project"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ac6316;\">Luteagraph</span></p></body></html>"))
        self.JumpManual.setText(_translate("MainWindow", " manual control"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#53515a;\">V.1.0</span></p></body></html>"))
        self.TabBar.setTabText(self.TabBar.indexOf(self.Home), _translate("MainWindow", "Home"))
        self.LoadFile.setText(_translate("MainWindow", " new project"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.FileSelector.setSortingEnabled(True)
        self.Pause.setText(_translate("MainWindow", "Pause"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.FileDescription.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#a1a4a3;\">File size: 103kB</span></p><p><span style=\" color:#a1a4a3;\">Date last modified: 11/23/2016</span></p><p><span style=\" color:#a1a4a3;\">File name: yeahboi.gcode</span></p></body></html>"))
        self.TimeEstimate.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#a1a4a3;\">Estimated time to completion: 45m 26s</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#a1a4a3;\">Speed: 45%</span></p></body></html>"))
        self.TabBar.setTabText(self.TabBar.indexOf(self.Project), _translate("MainWindow", "Project"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#40e2a0;\">X/Y</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#40e2a0;\">Z</span></p></body></html>"))
        self.TabBar.setTabText(self.TabBar.indexOf(self.Manual), _translate("MainWindow", "Manual"))
        self.label_6.setText(_translate("MainWindow", "No errors"))
        self.TabBar.setTabText(self.TabBar.indexOf(self.Error), _translate("MainWindow", "Error Dialogue"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

